//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompteResultat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TempOtherFields
    {
        public int ImportId { get; set; }
        public string ContractId { get; set; }
        public string Assureur { get; set; }
        public string Company { get; set; }
        public string Subsid { get; set; }
        public string Gestionnaire { get; set; }
        public string Apporteur { get; set; }
    }
}
