//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompteResultat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cadencier
    {
        public int Id { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<double> Cumul { get; set; }
        public Nullable<System.DateTime> DebutSurvenance { get; set; }
        public Nullable<System.DateTime> FinSurvenance { get; set; }
        public string AssureurName { get; set; }
    }
}
