//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompteResultat.DAL
{
    using System;
    
    public partial class CDemoData
    {
        public Nullable<int> Year { get; set; }
        public string Subsid { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public string Lien { get; set; }
        public string TrancheAge { get; set; }
        public Nullable<int> NombreAssure { get; set; }
        public Nullable<int> Age_Assur { get; set; }
        public string CodeCol { get; set; }
        public string FamColl { get; set; }
        public string SURCOM { get; set; }
    }
}
