//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompteResultat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompteResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompteResult()
        {
            this.CRPlannings = new HashSet<CRPlanning>();
            this.ReportDatas = new HashSet<ReportData>();
            this.ReportFiles = new HashSet<ReportFile>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsAutoGenerated { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> ReportLevelId { get; set; }
        public Nullable<int> CollegeId { get; set; }
        public string ContractIds { get; set; }
        public string SubsidIds { get; set; }
        public string AssurIds { get; set; }
        public Nullable<double> TaxDefault { get; set; }
        public Nullable<double> TaxActif { get; set; }
        public Nullable<double> TaxPerif { get; set; }
        public string ReportType { get; set; }
        public string CompanyIds { get; set; }
        public Nullable<int> CRAutoId { get; set; }
        public string LevelGrEnt { get; set; }
        public string RaisonSociale { get; set; }
        public string StructureCotisation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRPlanning> CRPlannings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportData> ReportDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportFile> ReportFiles { get; set; }
        public virtual CRAutoMain CRAutoMain { get; set; }
    }
}
