//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompteResultat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotisatSante
    {
        public int Id { get; set; }
        public int ImportId { get; set; }
        public string ContractId { get; set; }
        public string CodeCol { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> DebPrime { get; set; }
        public Nullable<System.DateTime> FinPrime { get; set; }
        public Nullable<double> Cotisation { get; set; }
        public string AssureurName { get; set; }
        public string Company { get; set; }
        public string Subsid { get; set; }
        public string WithOption { get; set; }
        public Nullable<double> CotisationBrute { get; set; }
        public string CodeSinistre { get; set; }
    }
}
