//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompteResultat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRAutoMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRAutoMain()
        {
            this.CompteResults = new HashSet<CompteResult>();
        }
    
        public int Id { get; set; }
        public string ListName { get; set; }
        public string ReporType { get; set; }
        public string MainFolderName { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompteResult> CompteResults { get; set; }
    }
}
