//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompteResultat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRGenListComp
    {
        public int Id { get; set; }
        public Nullable<int> CRListId { get; set; }
        public string GroupName { get; set; }
        public string Enterprise { get; set; }
        public string RaisonSociale { get; set; }
        public string StructureCotisation { get; set; }
    
        public virtual CRGenList CRGenList { get; set; }
    }
}
