//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompteResultat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRPlanning
    {
        public int Id { get; set; }
        public Nullable<int> CRId { get; set; }
        public Nullable<System.DateTime> DateArret { get; set; }
        public Nullable<System.DateTime> DebutPeriode { get; set; }
        public Nullable<System.DateTime> FinPeriode { get; set; }
        public Nullable<System.DateTime> DatePlanification { get; set; }
        public Nullable<System.DateTime> DateTraitement { get; set; }
        public Nullable<bool> CalcProv { get; set; }
    
        public virtual CompteResult CompteResult { get; set; }
    }
}
