//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompteResultat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FraisPrevoyance
    {
        public int Id { get; set; }
        public Nullable<int> AnneeSurvenance { get; set; }
        public string TypeSinistre { get; set; }
        public Nullable<double> Frais { get; set; }
    }
}
