//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompteResultat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupGarantySante
    {
        public int Id { get; set; }
        public string AssureurName { get; set; }
        public string GroupName { get; set; }
        public string GarantyName { get; set; }
        public string CodeActe { get; set; }
        public int OrderNumber { get; set; }
    }
}
