//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompteResultat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportFile
    {
        public int ID { get; set; }
        public int ImportId { get; set; }
        public string FileGroup { get; set; }
        public string FileType { get; set; }
        public string FileName { get; set; }
        public Nullable<int> NbRowsDb { get; set; }
        public Nullable<int> NbRowsCsv { get; set; }
        public Nullable<double> AmountDb { get; set; }
        public Nullable<double> AmountCsv { get; set; }
        public Nullable<int> DifferenceRows { get; set; }
        public Nullable<double> DifferenceAmount { get; set; }
        public Nullable<int> IsDifference { get; set; }
    }
}
