//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompteResultat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvPrev
    {
        public int Id { get; set; }
        public int ImportId { get; set; }
        public string AssureurName { get; set; }
        public string ContractId { get; set; }
        public string Company { get; set; }
        public string Subsid { get; set; }
        public string Dossier { get; set; }
        public string CodeCol { get; set; }
        public string Title { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<System.DateTime> DateSinistre { get; set; }
        public string NatureSinistre { get; set; }
        public string CauseSinistre { get; set; }
        public Nullable<System.DateTime> DebVal { get; set; }
        public Nullable<System.DateTime> FinVal { get; set; }
        public Nullable<System.DateTime> DateRecep { get; set; }
        public Nullable<System.DateTime> DateRechute { get; set; }
        public Nullable<System.DateTime> DateClo { get; set; }
        public string MotifClo { get; set; }
        public Nullable<System.DateTime> DatePayment { get; set; }
        public Nullable<System.DateTime> DateProvision { get; set; }
        public string Matricule { get; set; }
        public Nullable<double> Pm { get; set; }
        public Nullable<double> PmPassage { get; set; }
        public Nullable<double> Psap { get; set; }
        public Nullable<double> PmMgdc { get; set; }
        public Nullable<double> Psi { get; set; }
    }
}
