//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompteResultat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTemplate
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
        public Nullable<int> YearsToCalc { get; set; }
        public string Type { get; set; }
        public Nullable<bool> WithOption { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual ReportTemplate ReportTemplate1 { get; set; }
        public virtual ReportTemplate ReportTemplate2 { get; set; }
    }
}
