//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompteResultat.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportFile
    {
        public int Id { get; set; }
        public int CRId { get; set; }
        public string FileType { get; set; }
        public string FileLocation { get; set; }
    
        public virtual CompteResult CompteResult { get; set; }
    }
}
